---
spring:
  datasource:
    url: jdbc:mysql://db:3306/stocks
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
security:
  basic:
    enabled: false

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:stocksdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
