---
spring:
  datasource:
    url: jdbc:mysql://db:3306/stocks?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
security:
  basic:
    enabled: false
